export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_ERROR = 'FETCH_PHONES_ERROR';
export const DELETE_PHONE_SUCCESS = 'DELETE_PHONE_SUCCESS';
export const DELETE_PHONE_ERROR = 'DELETE_PHONE_ERROR';
export const ADD_PHONE_SUCCESS = 'ADD_PHONE_SUCCESS';
export const ADD_PHONE_ERROR = 'ADD_PHONE_ERROR';
export const EDIT_PHONE_SUCCESS = 'EDIT_PHONE_SUCCESS';
export const EDIT_PHONE_ERROR = 'EDIT_PHONE_ERROR';
